### ISSUE TITLE
Sequence as iterable

### ISSUE THREAD

**Issue by fcastan** [mikrosimage/sequenceparser#7]
Could be great to add a way to iter through existing files of a sequence (in C++ and Python). Sequence object could become a standard iterable:

for i in mySeq:
   print("existing file:", i)

for( Sequence::const_iterator it = mySeq.begin(), itEnd = mySeq.end(); it != itEnd; ++it )
{
    std::cout << *it << std::endl;
}

**Comment by cchampet** [comment]
Is this issue already done [here](https://github.com/mikrosimage/sequenceparser/blob/master/src/Sequence.hpp#L174)?

**Comment by fabiencastan** [comment]
yes
